language: objective-c  
osx_image: xcode8.0
xcode_workspace: TeslaSwift.xcworkspace
xcode_scheme: TeslaSwift
xcode_sdk: iphonesimulator10.0
notifications:
  email: false
before_install:
 - rvm install ruby-2.2.2
 - gem install cocoapods
