language: objective-c  
osx_image: xcode10.1
xcode_workspace: TeslaSwift.xcworkspace
xcode_scheme: TeslaSwift
xcode_sdk: iphonesimulator12.1
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XS
notifications:
  email: false
